"""Original PEFTLeak-style image adapter leakage helpers."""

from .core import (
    PatchStatistics,
    PeftLeakProbeStatistics,
    PeftLeakRecoveryResult,
    TorchvisionVitWithMaliciousAdapter,
    VitAdapterGradientResult,
    assign_peftleak_patch_slots,
    build_peftleak_probe_statistics,
    build_peftleak_probe_statistics_from_patch_stats,
    build_public_patch_statistics,
    build_shared_adapter_gradient_bundle,
    build_shared_adapter_gradients,
    build_vit_adapter_gradients,
    cluster_and_reassemble,
    design_malicious_adapter_parameters,
    load_public_patch_statistics,
    move_peftleak_probe_statistics,
    move_patch_statistics,
    optimize_patch_baseline,
    peftleak_expose_patches,
    recover_patch_from_adapter_grads,
    recover_patches_from_batch,
    recover_patches_from_named_adapter_grads,
    recover_patches_from_shared_adapter_grads,
    save_public_patch_statistics,
)
